# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_mlff.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help_MLFF(object):
    def setupUi(self, Help_MLFF):
        Help_MLFF.setObjectName("Help_MLFF")
        Help_MLFF.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Help_MLFF)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Help_MLFF)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(Help_MLFF)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(Help_MLFF)
        QtCore.QMetaObject.connectSlotsByName(Help_MLFF)

    def retranslateUi(self, Help_MLFF):
        _translate = QtCore.QCoreApplication.translate
        Help_MLFF.setWindowTitle(_translate("Help_MLFF", "Dialog"))
        self.label.setText(_translate("Help_MLFF", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">MLFF Help</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Help_MLFF", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">This Tab performs phonon and INS simulations for any given crystal using one of the pre-trained universal MLFFs (see Refs [8-12]). </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 1: Upload a crystal structure file. Currently supports CIF and VASP POSCAR formats. The CIF file name must end with &quot;.cif&quot;, and the VASP file name must contain &quot;POSCAR&quot; or &quot;CONTCAR&quot; for automatic recognition. If a structure file is successfully uploaded, the corresponding name will be displayed after &quot;Structure file:&quot;, and the crystal information will be displayed in the terminal as &quot;INFO&quot;. Optionally, you could also view the crystal structure. Note that the uploaded structure must represent a physical atomic configuration. Partial/fractional occupancies, as sometimes recorded in a CIF file, are not accepted. To denote vacancies or structural disorder, one must make a supercell to generate a physical representation of the local structure.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 2: Choose a pre-trained MLFF to use for the calculation.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 3: Structural optimization and phonon calculation. This step usually takes some time. The run time depends on the size and symmetry of the structure (number of degrees of freedom), the MLFF model, and the speed of the GPU/CPU. For relatively simple systems, it should take seconds to complete. For a large cell with low symmetry, it may take minutes or even hours. You can monitor the progress of the calculation in the terminal. There are four parameters you could set for this calculation.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Lmin: Minimum dimension for supercell (in Angstrom). Larger numbers may result in larger supercells and longer calculation time. (default: 12)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Fmax: Maximum force in an optimized structure (in eV/A), which is the criterion for stopping optimization. Smaller values will require more optimization steps. (default: 0.01)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Nmax: Maximum number of optimization steps. Optimization stops here even if the force criterion has not been met. (default: 100)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">detla: Atomic displacement in the finite displacement calculation (in A). (default: 0.03)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 4: Set up INS simulation (Phonopy and OCLIMAX). This step generates a *.params file in the working directory. Detailed instructions can be found in the popup window (the help button within).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 5: Run INS simulation. Depending on the size/complexity of the calculation, the time needed to complete this step can vary significantly. Monitor the terminal output for progress. Generally speaking, the run time is determined by the size of the mesh.yaml in the working directory, as well as the requested quality of the calculation (number of  E and Q bins). As a rule of thumb, the size of the mesh.yaml file should be smaller than 1GB (in most cases on the order of 10~100MB), the number of E bins should be less than a few thousand for 1D spectra, and the number of E and Q bins should be less than a few hundred each for 2D spectra. When in doubt, it is recommended to start from a relatively coarse calculation and then gradually increase the quality to achieve convergence without making the run time unacceptably long.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 6: Plot the resulting spectra. For 2D spectra, you may make an interactive cross-section plot where 1D cuts along X and Y will be displayed following the cursor. You may open multiple plots simultaneously. Data files will have a time stamp in their names so they are not overwritten.</span></p></body></html>"))
