# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_paths.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetPaths(object):
    def setupUi(self, SetPaths):
        SetPaths.setObjectName("SetPaths")
        SetPaths.resize(469, 176)
        self.verticalLayout = QtWidgets.QVBoxLayout(SetPaths)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(SetPaths)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_dp_path = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_dp_path.setObjectName("lineEdit_dp_path")
        self.horizontalLayout_2.addWidget(self.lineEdit_dp_path)
        self.pushButton_dp_path = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_dp_path.setObjectName("pushButton_dp_path")
        self.horizontalLayout_2.addWidget(self.pushButton_dp_path)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(SetPaths)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_dft_path = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_dft_path.setObjectName("lineEdit_dft_path")
        self.horizontalLayout.addWidget(self.lineEdit_dft_path)
        self.pushButton_dft_path = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_dft_path.setObjectName("pushButton_dft_path")
        self.horizontalLayout.addWidget(self.pushButton_dft_path)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButton_save = QtWidgets.QPushButton(SetPaths)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_4.addWidget(self.pushButton_save)
        self.pushButton_cancel = QtWidgets.QPushButton(SetPaths)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_4.addWidget(self.pushButton_cancel)
        self.pushButton_quit = QtWidgets.QPushButton(SetPaths)
        self.pushButton_quit.setToolTipDuration(-1)
        self.pushButton_quit.setStatusTip("")
        self.pushButton_quit.setWhatsThis("")
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.horizontalLayout_4.addWidget(self.pushButton_quit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(SetPaths)
        self.pushButton_dp_path.clicked.connect(SetPaths.browse_dp_model) # type: ignore
        self.pushButton_dft_path.clicked.connect(SetPaths.browse_dftdb) # type: ignore
        self.pushButton_quit.clicked.connect(SetPaths.quit_inspired) # type: ignore
        self.pushButton_save.clicked.connect(SetPaths.save_paths) # type: ignore
        self.pushButton_cancel.clicked.connect(SetPaths.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SetPaths)

    def retranslateUi(self, SetPaths):
        _translate = QtCore.QCoreApplication.translate
        SetPaths.setWindowTitle(_translate("SetPaths", "Set up simulation"))
        self.groupBox_2.setTitle(_translate("SetPaths", "Folder containing Predictor models (spectral and latent space predictors, decoder)"))
        self.pushButton_dp_path.setText(_translate("SetPaths", "Browse"))
        self.groupBox.setTitle(_translate("SetPaths", "Folder containing DFT database"))
        self.pushButton_dft_path.setText(_translate("SetPaths", "Browse"))
        self.pushButton_save.setText(_translate("SetPaths", "Save"))
        self.pushButton_cancel.setText(_translate("SetPaths", "Cancel"))
        self.pushButton_quit.setToolTip(_translate("SetPaths", "Click this botton will terminate INSPIRED."))
        self.pushButton_quit.setText(_translate("SetPaths", "Quit INSPIRED"))
