name: inspired-dev
channels:
  - conda-forge
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - toml
  - setuptools
  - pre-commit
  - python == 3.9.*
  - python-build
  - versioningit
  - pandas
  - qtpy
  - spglib==2.4.0
  - seekpath
  - phonopy==2.26.6
  - pymace
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - --find-links https://pytorch-geometric.com/whl/torch-2.2.0+cpu.html
    - torch==2.2.0
    - torchvision==0.17.0 
    - torchaudio==2.2.0
    - torch-geometric==2.5.3
    - torch-sparse
    - torch-scatter
    - torch-cluster
    - mattersim==1.0.0rc9
    - sevenn==0.10.4
    - pyqt5