name: inspired-dev
channels:
  - conda-forge
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - toml
  - setuptools
  - pre-commit
  - python == 3.10.*
  - python-build
  - versioningit
  - pandas
  - qtpy
  - spglib==2.6.0
  - seekpath
  - phonopy==2.28.0
  - pymace==0.3.10
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - --find-links https://pytorch-geometric.com/whl/torch-2.5.1+cpu.html
    - torch==2.5.1
    - torch-geometric==2.6.1
    - torch-sparse==0.6.18
    - torch-scatter==2.1.2
    - torch-cluster==1.6.3
    - mattersim==1.1.2
    - sevenn==0.11.0
    - e3nn==0.5.0
    - pyqt5
