# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_dft.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help_DFT(object):
    def setupUi(self, Help_DFT):
        Help_DFT.setObjectName("Help_DFT")
        Help_DFT.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Help_DFT)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Help_DFT)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(Help_DFT)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(Help_DFT)
        QtCore.QMetaObject.connectSlotsByName(Help_DFT)

    def retranslateUi(self, Help_DFT):
        _translate = QtCore.QCoreApplication.translate
        Help_DFT.setWindowTitle(_translate("Help_DFT", "Dialog"))
        self.label.setText(_translate("Help_DFT", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">DFT Help</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Help_DFT", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">This Tab performs INS simulations based on provided DFT results, either from the included DFT database or the user\'s own DFT calculations. The DFT database contains 11,429 entries, including 10,023 from phonondb (see Ref. [4] in the About tab) and 1,406 from the current author (unpublished). Data files required (POSCAR-unitcell, FORCE_SETS or FORCE_CONSTANTS, mesh.conf, and in some cases BORN) as input for INS calculations are already available. You may also choose to use your own DFT calculation results, in which case check &quot;Use My DFT Data&quot; and specify the folder containing the above files.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">If you use the database, you may search the entries in different ways (the &quot;Type&quot; dropdown list). The search &quot;Value&quot; may contain wildcards as long as it is a valid regex. Once you find the crystal, click on it to choose.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 2 is optional, but it is often convenient to check the phonon dispersion and DOS before the INS simulation. In some cases, negative frequencies (imaginary modes) exist, which could indicate insufficient modeling or true instability of the structure. It is important to be aware of this situation when interpreting the results.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 3: Setup INS simulation (Phonopy and OCLIMAX). This step generates a *.params file in the working directory. Detailed instructions can be found in the popup window.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 4: Run INS simulation. Depending on the size/complexity of the calculation, the time needed to complete this step can vary a lot. Monitor the terminal output for progress. Generally speaking, the run time is determined by the size of the mesh.yaml in the working directory, as well as how fine the calculation is (number of  E and Q bins). As a rule of thumb, the size of the mesh.yaml file should be smaller than 1GB (in most cases on the order of 10~100MB), the number of E bins should be less than 1000 for 1D spectra, and the number of E and Q bins should be less than a few hundred each for 2D spectra. When in doubt, it is recommended to start from a relatively coarse calculation and then gradually increase the accuracy to achieve convergence without making the run time unacceptably long.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 4: Plot the resulting spectra. For 2D specra, you may make an interactive cross-section plot where 1D cuts along X and Y will be displayed following the cursor. You may open multiple plots simultaneously. Data files will have a time-stamp in the file names so they are not overwritten.</span></p></body></html>"))
