# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_dp.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Help_DP(object):
    def setupUi(self, Help_DP):
        Help_DP.setObjectName("Help_DP")
        Help_DP.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Help_DP)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Help_DP)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(Help_DP)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(Help_DP)
        QtCore.QMetaObject.connectSlotsByName(Help_DP)

    def retranslateUi(self, Help_DP):
        _translate = QtCore.QCoreApplication.translate
        Help_DP.setWindowTitle(_translate("Help_DP", "Dialog"))
        self.label.setText(_translate("Help_DP", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Predictor Help</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("Help_DP", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">This Tab performs direct prediction of phonon DOS or INS spectra from the crystal structure. The energy range is 0~150 meV and the Q range is 0~15 A</span><span style=\" font-size:12pt; vertical-align:super;\">-1</span><span style=\" font-size:12pt;\">.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 1: Upload a crystal structure file. Currently supports CIF and VASP POSCAR formats. The CIF file name must end with &quot;.cif&quot;, and the VASP file name must contain &quot;POSCAR&quot; or &quot;CONTCAR&quot; for automatic recognition. If a structure file is successfully uploaded, the corresponding name will be displayed after &quot;Structure file:&quot;, and the crystal information will be displayed in the terminal as &quot;INFO&quot;. Note that the uploaded structure must represent a physical atomic configuration. Partial/fractional occupancies, as usually recorded in a CIF file, are not accepted. To denote vacancies or structural disorder, one must make a supercell to generate a physical representative of the local structure.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 2: Perform prediction. You may choose one from the three options: phonon DOS, VISION spectra, or 2D S(Q,E). Click the &quot;Predict&quot; button to run the prediction, which usually takes less than a few seconds. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Step 3: Plot the results (and save the predicted spectra to csv files). For 2D S(Q,E), you may make an interactive cross-section plot where 1D cuts along E and Q will be displayed following the cursor. You may open multiple plots simultaneously. Data files will have a time stamp in their names so they are not overwritten.</span></p></body></html>"))
