name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next]
    tags: ["v*"]

# cancel previous job if new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PKG_NAME: inspired

jobs:
  tests:
    name: Testing Suite
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3

      - name: pylint
        run: pixi run pre-commit run -a ruff

      - name: Install inspired
        run: pixi run python -m pip install -e .

  build:
    name: Conda build with Pixi
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3

      - name: Build Conda package
        run: |
          pixi run conda-build
          mkdir -p /tmp/local-channel/linux-64
          cp *.conda /tmp/local-channel/linux-64

      - name: Verify conda package
        uses: neutrons/conda-verify@main
        with:
          package-name: inspired
          local-channel: /tmp/local-channel
          python-version: "3.12"
          extra-channels: conda-forge

      - name: Upload conda package as artifact
        uses: actions/upload-artifact@v6
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: artifact-conda-package
          path: ${{ env.PKG_NAME }}-*.conda

  publish:
    name: Publish
    runs-on: ubuntu-24.04
    needs: [tests, build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 100
          fetch-tags: true
          ref: ${{ github.ref }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3

      - name: Download previous conda package artifact
        uses: actions/download-artifact@v7
        with:
          name: artifact-conda-package

      - name: Get artifact conda package filename
        run: |
          echo "Files downloaded:"
          ls
          # Get the first file
          FILE_NAME=$(ls ./${{ env.PKG_NAME }}-*.conda)
          echo "Conda package file to publish: $FILE_NAME"

      - name: Upload package to anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          IS_RC: ${{ contains(github.ref, 'rc') }}
        run: |
          # label is main or rc depending on the tag-name
          CONDA_LABEL="main"
          if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
          echo pushing ${{ github.ref }} with label $CONDA_LABEL
          pixi run anaconda upload --label $CONDA_LABEL --user neutrons ${{ env.PKG_NAME }}-*.conda

  # Trigger GitLab dev deploy pipeline
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    # if: github.ref == 'refs/heads/next'
    permissions: write-all
    steps:
      - name: Get Environment Name
        uses: neutrons/branch-mapper@main
        id: env_name
        with:
          prefix: ${{ env.PKG_NAME }}

      - name: Trigger Dev Deploy
        # use https://github.com/eic/trigger-gitlab-ci/pull/14 until merged
        uses: eic/trigger-gitlab-ci@d984d8d53d871d2fdc1325639d94322da6e8747f
        id: trigger
        with:
          url: https://code.ornl.gov
          project_id: 17827
          ref_name: main
          token: ${{ secrets.GITLAB_DEPLOY_TOKEN }}

      - name: Annotate commit
        uses: peter-evans/commit-comment@v4
        with:
          body: |
            GitLab pipeline for ${{ steps.env_name.outputs.name }} has been submitted for this commit: ${{ steps.trigger.outputs.web_url }}
